### ISSUE TITLE
Linear Distribution to Gaussian

### ISSUE THREAD

**Issue by YoureATowel** [emipa606/VariedBodySizes#18]
While back you mentioned you were interested in adding in normal distribution curve for size - there are some complex calculations (Box muller transforms plus others) but you can also get a good simple normal distribution just by adding up several rands, adjusting the min/max and # of rolls to get your preferred distribution while keeping the actual math much simpler

was straightforward to modify to get a good gaussian distribution: 

 return (float)Math.Round((Rand.Range(100f, 200f) + [repeat rand for each roll]) / ([rangemin+rangemax/2] * [# rolls]), 2);
add up all the rand rolls and divide by [rangemin+rangemax/2] * [#rolls] to get the % of standard body size

playing around with a spreadsheet simulation can get you some good ranges for several setting options

Below is an example (tho arbitrary) range of options. Infinite number of other options, but really the stdev is all that matters here and there are multiple ways to adjust that

Option	Min	Max	Rolls	stdev	2 stdev (>97% pawns)	3 stdev (>99% pawns)
Realistic	200	300	10	         3%     	1.06	                                 1.09
Default	100	200	10	         6%  	1.12	                                 1.18
High 	50	150	10           	9%   	1.18	                               	1.27
Extreme	25	125	10	        12% 	1.24		                         1.36

No idea how to use github so not sure if this is the correct place to add this

**Comment by emipa606** [comment]
Would this be a good implementation?
```csharp
var sizeRange = VariedBodySizesMod.instance.Settings.DefaultVariation;
var standardDeviationDivider= VariedBodySizesMod.instance.Settings.StandardDeviationDivider;
var randomStandardNormal = Math.Sqrt(-2.0 * Math.Log(Rand.Value)) * Math.Sin(2.0 * Math.PI * Rand.Value);
var mean = (sizeRange.min + sizeRange.max) / 2;
var standardDeviation = (sizeRange.max - sizeRange.min) / standardDeviationDivider;
return mean + standardDeviation* randomStandardNormal;
```
And then vary the standardDeviationDivider value with a mod-setting?

**Comment by YoureATowel** [comment]
Yep that's beautiful! Spreadsheet sim puts out a [really nice gaussian](https://i.imgur.com/dg0cXYI.png)

May be better to have user-set mean (or default to 1) instead of using min/max avg, in case someone sets their range unevenly (ex 80%-150%) - users may not know why all their pawns are above 100% size, or may intentionally want a distribution centered around a different size.

Min/max isn't super important compared to mean and stdev (and is arguably not needed) except in cases where the user sets the min/max bounds within 1-3 stdevs. If it's set too close it'll result in a large number of pawns being rounded to that min/max, potentially leading to a U-shaped distribution. Like if I set stdev to 15% but set my min/max as .8-1.2 I will have a ton of pawns rounded to .exactly 8 and 1.2 size. Nothing really wrong with this and nice to have min/max option, just something to keep in mind in case users wonder why so many of their pawns are at the min/max. Could potentially default to no min/max (or set to wide values like 0.1-5) when using gaussian distribution, or force it to be at least 3x stdevs from mean, or recommend to user that they dont put it too close to mean.

**Comment by emipa606** [comment]
I added it in c4d94bd
Hopfully the implementation is good enough.
Thanks for the info!
