### ISSUE TITLE
Update for 1.5

### ISSUE THREAD

**Issue by emipa606** [emipa606/VariedBodySizes#21]
I know too little about transpilers to get this to work after the changes in pawn-rendering in 1.5.
@oorzkws do you think you could take a look at it perhaps?

**Comment by oorzkws** [comment]
I'm very sorry for the delay in expansion support. I'll take a look, it's a pretty hectic few weeks until Factorio Space Age releases, though.

**Comment by emipa606** [comment]
No worries!

**Comment by oorzkws** [comment]
[39aee8b9a88104dab4da69f0c834e0822f834665](https://github.com/oorzkws/VariedBodySizes/commit/39aee8b9a88104dab4da69f0c834e0822f834665)
Humans are mostly in order now. Some stuff like the offset on tails is weird, but I don't think that looked good before.
![image](https://github.com/user-attachments/assets/cc03cc07-ca45-4548-bad7-ea188b033e77)

Animals aren't scaling, will need to look into it.

**Comment by emipa606** [comment]
Nice, Ive published it for now!
