### ISSUE TITLE
Incompatibility With NL Apparel Paper Pattern

### ISSUE THREAD

**Issue by Spaaace56** [emipa606/VariedBodySizes#8]
[Hugs Log.txt](https://github.com/emipa606/VariedBodySizes/files/10468568/Hugs.Log.txt)

**Comment by emipa606** [comment]
Looking at it I dont think I have any time to add compatibility with such a mod. I think they will have it easier fixing it on their end as this mods size-definitions is a public property that can be used simply on their end to set their drawsizes.
