### ISSUE TITLE
Fix cache duration

### ISSUE THREAD

**Issue by oorzkws** [emipa606/VariedBodySizes#9]
Gotten a bug-rerport that seems to be connected to the caching of the stat-values. Could you take a look?
https://discord.com/channels/680705672911913016/693732045100154910/1078445040428392498

_Originally posted by @emipa606 in https://github.com/emipa606/VariedBodySizes/issues/5#issuecomment-1442542076_

Editor's note: I'm probably caching far too long, perf gains should be seen after a second of caching after all.

**Comment by oorzkws** [comment]
kindly assign me @emipa606

**Comment by oorzkws** [comment]
tracking at https://github.com/oorzkws/VariedBodySizes/tree/bugfix-cache

**Comment by emipa606** [comment]
Fixed in 5c2b768
